/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_opencvdemos_TwoActivity */

#ifndef _Included_com_demo_opencvdemos_TwoActivity
#define _Included_com_demo_opencvdemos_TwoActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_demo_opencvdemos_TwoActivity_VIEW_MODE_RGBA
#define com_demo_opencvdemos_TwoActivity_VIEW_MODE_RGBA 0L
#undef com_demo_opencvdemos_TwoActivity_VIEW_MODE_GRAY
#define com_demo_opencvdemos_TwoActivity_VIEW_MODE_GRAY 1L
#undef com_demo_opencvdemos_TwoActivity_VIEW_MODE_CANNY
#define com_demo_opencvdemos_TwoActivity_VIEW_MODE_CANNY 2L
#undef com_demo_opencvdemos_TwoActivity_VIEW_MODE_FEATURE
#define com_demo_opencvdemos_TwoActivity_VIEW_MODE_FEATURE 3L
/*
 * Class:     com_demo_opencvdemos_TwoActivity
 * Method:    findFeatures
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_demo_opencvdemos_TwoActivity_findFeatures
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
